"""Constants for the Sunsynk integration."""

from homeassistant.const import Platform

import voluptuous as vol

import homeassistant.helpers.config_validation as cv

DOMAIN = "solar_sunsynk"
PLATFORMS = [Platform.SENSOR, Platform.BUTTON, Platform.SWITCH, Platform.NUMBER, Platform.TEXT, Platform.SELECT]

NAME = "Solar Sunsynk"
ISSUE_URL = "https://github.com/MorneSaunders360/Solar-Sunsynk/issues"

STARTUP_MESSAGE = f"""
-------------------------------------------------------------------
{NAME}
This is a custom integration!
If you have any issues with this you need to open an issue here:
{ISSUE_URL}
-------------------------------------------------------------------
"""
SetSolarSettingsSchema = vol.Schema(
    {
        vol.Required("sn"): cv.string,
        vol.Optional("safetyType"): cv.string,
        vol.Optional("battMode"): cv.string,
        vol.Optional("solarSell"): cv.string,
        vol.Optional("pvMaxLimit"): cv.string,
        vol.Optional("energyMode"): cv.string,
        vol.Optional("peakAndVallery"): cv.string,
        vol.Optional("sysWorkMode"): cv.string,
        vol.Optional("sellTime1"): cv.string,
        vol.Optional("sellTime2"): cv.string,
        vol.Optional("sellTime3"): cv.string,
        vol.Optional("sellTime4"): cv.string,
        vol.Optional("sellTime5"): cv.string,
        vol.Optional("sellTime6"): cv.string,
        vol.Optional("sellTime1Pac"): cv.string,
        vol.Optional("sellTime2Pac"): cv.string,
        vol.Optional("sellTime3Pac"): cv.string,
        vol.Optional("sellTime4Pac"): cv.string,
        vol.Optional("sellTime5Pac"): cv.string,
        vol.Optional("sellTime6Pac"): cv.string,
        vol.Optional("cap1"): cv.string,
        vol.Optional("cap2"): cv.string,
        vol.Optional("cap3"): cv.string,
        vol.Optional("cap4"): cv.string,
        vol.Optional("cap5"): cv.string,
        vol.Optional("cap6"): cv.string,
        vol.Optional("sellTime1Volt"): cv.string,
        vol.Optional("sellTime2Volt"): cv.string,
        vol.Optional("sellTime3Volt"): cv.string,
        vol.Optional("sellTime4Volt"): cv.string,
        vol.Optional("sellTime5Volt"): cv.string,
        vol.Optional("sellTime6Volt"): cv.string,
        vol.Optional("sellTime1En"): cv.string,
        vol.Optional("sellTime2En"): cv.string,
        vol.Optional("sellTime3En"): cv.string,
        vol.Optional("sellTime4En"): cv.string,
        vol.Optional("sellTime5En"): cv.string,
        vol.Optional("sellTime6En"): cv.string,
        vol.Optional("zeroExportPower"): cv.string,
        vol.Optional("solarMaxSellPower"): cv.string,
        vol.Optional("gridPeakShaving"): cv.string,
        vol.Optional("lowVoltCrossEn"): cv.string,
        vol.Optional("generatorStartCap"): cv.string,
        vol.Optional("batteryLowCap"): cv.string,
        vol.Optional("mondayOn"): cv.boolean,
        vol.Optional("tuesdayOn"): cv.boolean,
        vol.Optional("wednesdayOn"): cv.boolean,
        vol.Optional("thursdayOn"): cv.boolean,
        vol.Optional("fridayOn"): cv.boolean,
        vol.Optional("saturdayOn"): cv.boolean,
        vol.Optional("sundayOn"): cv.boolean,
        vol.Optional("time1on"): cv.boolean,
        vol.Optional("time2on"): cv.boolean,
        vol.Optional("time3on"): cv.boolean,
        vol.Optional("time4on"): cv.boolean,
        vol.Optional("time5on"): cv.boolean,
        vol.Optional("time6on"): cv.boolean,
        vol.Optional("genTime1on"): cv.boolean,
        vol.Optional("genTime2on"): cv.boolean,
        vol.Optional("genTime3on"): cv.boolean,
        vol.Optional("genTime4on"): cv.boolean,
        vol.Optional("genTime5on"): cv.boolean,
        vol.Optional("genTime6on"): cv.boolean,
        vol.Optional("sellTime1on"): cv.boolean,
        vol.Optional("sellTime2on"): cv.boolean,
        vol.Optional("sellTime3on"): cv.boolean,
        vol.Optional("sellTime4on"): cv.boolean,
        vol.Optional("sellTime5on"): cv.boolean,
        vol.Optional("sellTime6on"): cv.boolean,
    }
)

SetBatterySettingsSchema = vol.Schema(
    {
        vol.Required("sn"): cv.string,
        vol.Optional("safetyType"): cv.string,
        vol.Optional("battMode"): cv.string,
        vol.Optional("batteryCap"): cv.string,
        vol.Optional("batteryMaxCurrentCharge"): cv.string,
        vol.Optional("batteryMaxCurrentDischarge"): cv.string,
        vol.Optional("batteryEmptyV"): cv.string,
        vol.Optional("batteryImpedance"): cv.string,
        vol.Optional("batteryEfficiency"): cv.string,
        vol.Optional("batteryShutdownCap"): cv.string,
        vol.Optional("batteryLowCap"): cv.string,
        vol.Optional("batteryRestartCap"): cv.string,
        vol.Optional("batteryShutdownVolt"): cv.string,
        vol.Optional("batteryLowVolt"): cv.string,
        vol.Optional("batteryRestartVolt"): cv.string,
        vol.Optional("batteryOn"): cv.string,
        vol.Optional("floatVolt"): cv.string,
        vol.Optional("lithiumMode"): cv.string,
        vol.Optional("sdChargeOn"): cv.string,
        vol.Optional("sdStartCap"): cv.string,
        vol.Optional("sdBatteryCurrent"): cv.string,
        vol.Optional("genChargeOn"): cv.string,
        vol.Optional("sdStartVol"): cv.string,
        vol.Optional("gridSignal"): cv.string,
        vol.Optional("generatorStartVolt"): cv.string,
        vol.Optional("generatorStartCap"): cv.string,
        vol.Optional("generatorBatteryCurrent"): cv.string,
        vol.Optional("equChargeCycle"): cv.string,
        vol.Optional("equChargeTime"): cv.string,
        vol.Optional("absorptionVolt"): cv.string,
        vol.Optional("equVoltCharge"): cv.string,
        vol.Optional("tempco"): cv.string,
        vol.Optional("genSignal"): cv.string,
        vol.Optional("sdStartVolt"): cv.string,
        vol.Optional("generatorForcedStart"): cv.string,
        vol.Optional("bmsErrStop"): cv.string,
        vol.Optional("signalIslandModeEnable"): cv.string,
        vol.Optional("lowPowerMode"): cv.string,
        vol.Optional("disableFloatCharge"): cv.string,
        vol.Optional("lowNoiseMode"): cv.string,
        vol.Optional("flag2"): cv.string,
    }
)

SetBasicSettingsSchema = vol.Schema(
    {
        vol.Required("sn"): cv.string,
        vol.Optional("timeSync"): cv.string,
        vol.Optional("beep"): cv.string,
        vol.Optional("ampm"): cv.string,
        vol.Optional("autoDim"): cv.string,
        vol.Optional("lockOutChange"): cv.string,
    }
)

SetAuxiliaryLoadSettingsSchema = vol.Schema(
    {
        vol.Required("sn"): cv.string,
        vol.Optional("safetyType"): cv.string,
        vol.Optional("battMode"): cv.string,
        vol.Optional("genMinSolar"): cv.string,
        vol.Optional("loadMode"): cv.string,
        vol.Optional("genOffCap"): cv.string,
        vol.Optional("genOnCap"): cv.string,
        vol.Optional("genOffVolt"): cv.string,
        vol.Optional("genOnVolt"): cv.string,
        vol.Optional("gridAlwaysOn"): cv.string,
        vol.Optional("offGridImmediatelyOff"): cv.string,
        vol.Optional("acCoupleFreqUpper"): cv.string,
        vol.Optional("genConnectGrid"): cv.string,
        vol.Optional("genPeakShaving"): cv.string,
        vol.Optional("genPeakPower"): cv.string,
        vol.Optional("acCoupleOnLoadSideEnable"): cv.string,
        vol.Optional("acCoupleOnGridSideEnable"): cv.string,
    }
)

SetAdvancedSettingsSchema = vol.Schema(
    {
        vol.Required("sn"): cv.string,
        vol.Optional("parallel"): cv.string,
        vol.Optional("equipMode"): cv.string,
        vol.Optional("modbusSn"): cv.string,
        vol.Optional("phase"): cv.string,
        vol.Optional("externalCtRatio"): cv.string,
        vol.Optional("meterSelect"): cv.string,
        vol.Optional("gridSideINVMeter2"): cv.string,
        vol.Optional("solarMaxSellPower"): cv.string,
    }
)

SetGridSettingsSchema = vol.Schema(
    {
        vol.Required("sn"): cv.string,
        vol.Optional("genPeakShaving"): cv.string,
        vol.Optional("gridPeakShaving"): cv.string,
        vol.Optional("gridPeakPower"): cv.string,
        vol.Optional("parallel"): cv.string,
        vol.Optional("modbusSn"): cv.string,
        vol.Optional("sensorsCheck"): cv.string,
        vol.Optional("remoteLock"): cv.string,
        vol.Optional("gridAlwaysOn"): cv.string,
        vol.Optional("micExportGridOff"): cv.string,
        vol.Optional("bmsErrStop"): cv.string,
        vol.Optional("exMeterCtSwitch"): cv.string,
        vol.Optional("meterA"): cv.string,
        vol.Optional("meterB"): cv.string,
        vol.Optional("meterC"): cv.string,
        vol.Optional("atsEnable"): cv.string,
        vol.Optional("atsSwitch"): cv.string,
        vol.Optional("meterSelect"): cv.string,
        vol.Optional("gridSideINVMeter2"): cv.string,
        vol.Optional("smartCTEnable"): cv.string,
        vol.Optional("equipMode"): cv.string,
        vol.Optional("solarMaxSellPower"): cv.string,
        vol.Optional("drmEnable"): cv.string,
        vol.Optional("backupDelay"): cv.string,
        vol.Optional("solar1WindInputEnable"): cv.string,
        vol.Optional("solar2WindInputEnable"): cv.string,
        vol.Optional("solar3WindInputEnable"): cv.string,
        vol.Optional("solar2WindInputEn"): cv.string,
        vol.Optional("solar3WindInputEn"): cv.string,
        vol.Optional("phase"): cv.string,
        vol.Optional("volt1"): cv.string,
        vol.Optional("volt2"): cv.string,
        vol.Optional("volt3"): cv.string,
        vol.Optional("volt4"): cv.string,
        vol.Optional("volt5"): cv.string,
        vol.Optional("volt6"): cv.string,
        vol.Optional("volt7"): cv.string,
        vol.Optional("volt8"): cv.string,
        vol.Optional("volt9"): cv.string,
        vol.Optional("volt10"): cv.string,
        vol.Optional("volt11"): cv.string,
        vol.Optional("volt12"): cv.string,
        vol.Optional("current1"): cv.string,
        vol.Optional("current2"): cv.string,
        vol.Optional("current3"): cv.string,
        vol.Optional("current4"): cv.string,
        vol.Optional("current5"): cv.string,
        vol.Optional("current6"): cv.string,
        vol.Optional("current7"): cv.string,
        vol.Optional("current8"): cv.string,
        vol.Optional("current9"): cv.string,
        vol.Optional("current10"): cv.string,
        vol.Optional("current11"): cv.string,
        vol.Optional("current12"): cv.string,
        vol.Optional("signalIslandModeEnable"): cv.string,
        vol.Optional("isletProtect"): cv.string,
        vol.Optional("mpptMulti"): cv.string,
        vol.Optional("pv1SelfCheck"): cv.string,
        vol.Optional("pv2SelfCheck"): cv.string,
        vol.Optional("pv3SelfCheck"): cv.string,
        vol.Optional("acOutputPowerLimit"): cv.string,
        vol.Optional("risoEn"): cv.string,
        vol.Optional("pwm"): cv.string,
        vol.Optional("nightPowerSave"): cv.string,
        vol.Optional("earthBond"): cv.string,
        vol.Optional("codeMode"): cv.string,
        vol.Optional("smartMeter2Enable"): cv.string,
        vol.Optional("tenOverVoltEn"): cv.string,
        vol.Optional("tenOverVoltVal"): cv.string,
        vol.Optional("genToLoad"): cv.string,
        vol.Optional("exMeterCT"): cv.string,
        vol.Optional("genConnectGrid"): cv.string,
        vol.Optional("genPeakPower"): cv.string,
        vol.Optional("arcFactFrz"): cv.string,
    }
)
